[settings.npm]
bun = true

[settings.pipx]
uvx = true

[tools]
bat = "latest"
bun = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
helm = "latest"
jq = "latest"
kubectl = "latest"
lazygit = "latest"
lua-language-server = "latest"
node = "lts"
pnpm = "latest"
python = "3.11"
ripgrep = "latest"
shfmt = "latest"
stylua = "latest"
terraform = "latest"
uv = "latest"
wrangler = "latest"
yarn = "latest"
yq = "latest"

"asdf:richin13/asdf-neovim" = "latest"

"npm:bash-language-server" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:doctoc" = "latest"
"npm:mcp-hub" = "latest"
"npm:prettier" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:@astrojs/language-server" = "latest"
"npm:@github/copilot" = "latest"
"npm:@upstash/context7-mcp" = "latest"

"pipx:ansible-core" = { version = "latest", uvx_args = "--with ansible --with cryptography --with kubernetes --with passlib" }
"pipx:huggingface_hub[cli]" = "latest"
"pipx:kaggle" = "latest"
"pipx:markitdown" = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
"pipx:wandb" = "latest"
